# Generated by Django 4.2.2 on 2023-11-20 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_it', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
